/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    services: Service;
    products: Product;
    testimonials: Testimonial;
    posts: Post;
    leads: Lead;
    plans: Plan;
    partners: Partner;
    faqs: Faq;
    subscribers: Subscriber;
    media: Media;
    'help-articles': HelpArticle;
    projects: Project;
    'data-requests': DataRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'help-articles': HelpArticlesSelect<false> | HelpArticlesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'data-requests': DataRequestsSelect<false> | DataRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-content': SiteContent;
  };
  globalsSelect: {
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL anchor, e.g. web-development
   */
  slug: string;
  tagline?: string | null;
  /**
   * Short one-liner used on cards
   */
  description: string;
  /**
   * Wide intro shown at the top of the service page
   */
  overview?: string | null;
  /**
   * Emoji or short glyph, e.g. </> or ✦
   */
  icon?: string | null;
  accent?:
    | (
        | 'from-cyan-glow to-violet-glow'
        | 'from-violet-glow to-pink-glow'
        | 'from-pink-glow to-cyan-glow'
        | 'from-cyan-glow to-pink-glow'
        | 'from-violet-glow to-cyan-glow'
      )
    | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        benefit: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Detailed content blocks on the service page
   */
  sections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional pricing tiers shown on this service's page
   */
  pricing?:
    | {
        name: string;
        /**
         * e.g. from $990 — leave blank for 'Get a quote'
         */
        price?: string | null;
        /**
         * e.g. once-off, per month
         */
        unit?: string | null;
        features?:
          | {
              feature: string;
              id?: string | null;
            }[]
          | null;
        highlight?: boolean | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers show first
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * URL segment, e.g. web-hosting
   */
  slug: string;
  /**
   * Short one-liner used on cards
   */
  description: string;
  /**
   * Wide intro on the product page
   */
  overview?: string | null;
  icon?: string | null;
  /**
   * External order link (hosting portal)
   */
  href: string;
  price?: string | null;
  /**
   * Show the 'Popular' badge
   */
  highlight?: boolean | null;
  bullets?:
    | {
        bullet: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Detailed content blocks on the product page
   */
  sections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  role?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL segment, e.g. why-website-speed-matters
   */
  slug: string;
  /**
   * Short summary shown on cards & meta description
   */
  excerpt: string;
  coverImage?: (number | null) | Media;
  category?: string | null;
  author?: string | null;
  /**
   * Drafts are hidden from the public blog
   */
  status?: ('draft' | 'published') | null;
  date: string;
  /**
   * Estimated read time in minutes
   */
  readMins?: number | null;
  /**
   * Article body. Separate paragraphs with a blank line.
   */
  body: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  service?: string | null;
  message: string;
  status?: ('new' | 'in-progress' | 'won' | 'closed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  category: 'Google Workspace' | 'Microsoft 365' | 'Website Packages' | 'Marketing & SEO';
  name: string;
  blurb?: string | null;
  /**
   * AUD ex-GST, billed yearly (e.g. 8.40). Leave blank for 'Get a quote'.
   */
  priceAnnual?: string | null;
  /**
   * AUD ex-GST, flexible/monthly (e.g. 10.10).
   */
  priceMonthly?: string | null;
  /**
   * e.g. per user / month
   */
  unit?: string | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show as the featured plan
   */
  highlight?: boolean | null;
  ctaLabel?: string | null;
  /**
   * Order link or /contact
   */
  ctaHref?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logoMedia?: (number | null) | Media;
  /**
   * Or paste a logo image URL (upload above is preferred)
   */
  logo?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * Where they subscribed from (footer, blog, …)
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-articles".
 */
export interface HelpArticle {
  id: number;
  title: string;
  slug: string;
  category?: string | null;
  excerpt?: string | null;
  /**
   * Separate paragraphs with a blank line.
   */
  body: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  industry?: string | null;
  services?:
    | {
        service: string;
        id?: string | null;
      }[]
    | null;
  summary?: string | null;
  beforeMedia?: (number | null) | Media;
  afterMedia?: (number | null) | Media;
  /**
   * Or paste a 'before' image URL (upload preferred)
   */
  beforeImage?: string | null;
  /**
   * Or paste an 'after' image URL (upload preferred)
   */
  afterImage?: string | null;
  /**
   * Live site URL (optional)
   */
  url?: string | null;
  results?:
    | {
        result: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-requests".
 */
export interface DataRequest {
  id: number;
  email: string;
  type: 'export' | 'delete';
  details?: string | null;
  status?: ('new' | 'in-progress' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'help-articles';
        value: number | HelpArticle;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'data-requests';
        value: number | DataRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  overview?: T;
  icon?: T;
  accent?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        name?: T;
        price?: T;
        unit?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        highlight?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  overview?: T;
  icon?: T;
  href?: T;
  price?: T;
  highlight?: T;
  bullets?:
    | T
    | {
        bullet?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  category?: T;
  author?: T;
  status?: T;
  date?: T;
  readMins?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  blurb?: T;
  priceAnnual?: T;
  priceMonthly?: T;
  unit?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  highlight?: T;
  ctaLabel?: T;
  ctaHref?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logoMedia?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-articles_select".
 */
export interface HelpArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  body?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  industry?: T;
  services?:
    | T
    | {
        service?: T;
        id?: T;
      };
  summary?: T;
  beforeMedia?: T;
  afterMedia?: T;
  beforeImage?: T;
  afterImage?: T;
  url?: T;
  results?:
    | T
    | {
        result?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-requests_select".
 */
export interface DataRequestsSelect<T extends boolean = true> {
  email?: T;
  type?: T;
  details?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  /**
   * Headline numbers shown on the homepage & about page
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The 'How we work' steps on the homepage
   */
  processSteps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}