/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    customers: CustomerAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    services: Service;
    products: Product;
    software: Software;
    testimonials: Testimonial;
    posts: Post;
    authors: Author;
    leads: Lead;
    plans: Plan;
    partners: Partner;
    faqs: Faq;
    subscribers: Subscriber;
    media: Media;
    'help-articles': HelpArticle;
    projects: Project;
    'data-requests': DataRequest;
    customers: Customer;
    orders: Order;
    subscriptions: Subscription;
    invoices: Invoice;
    transactions: Transaction;
    'client-domains': ClientDomain;
    assets: Asset;
    tickets: Ticket;
    coupons: Coupon;
    'legal-pages': LegalPage;
    'case-studies': CaseStudy;
    quotes: Quote;
    'system-components': SystemComponent;
    incidents: Incident;
    onboarding: Onboarding;
    'status-subscribers': StatusSubscriber;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    software: SoftwareSelect<false> | SoftwareSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'help-articles': HelpArticlesSelect<false> | HelpArticlesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'data-requests': DataRequestsSelect<false> | DataRequestsSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    subscriptions: SubscriptionsSelect<false> | SubscriptionsSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'client-domains': ClientDomainsSelect<false> | ClientDomainsSelect<true>;
    assets: AssetsSelect<false> | AssetsSelect<true>;
    tickets: TicketsSelect<false> | TicketsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    'system-components': SystemComponentsSelect<false> | SystemComponentsSelect<true>;
    incidents: IncidentsSelect<false> | IncidentsSelect<true>;
    onboarding: OnboardingSelect<false> | OnboardingSelect<true>;
    'status-subscribers': StatusSubscribersSelect<false> | StatusSubscribersSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-content': SiteContent;
    'page-content': PageContent;
    'site-settings': SiteSetting;
    'billing-settings': BillingSetting;
  };
  globalsSelect: {
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
    'page-content': PageContentSelect<false> | PageContentSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'billing-settings': BillingSettingsSelect<false> | BillingSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Customer;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface CustomerAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * URL anchor, e.g. web-development
   */
  slug: string;
  tagline?: string | null;
  /**
   * Short one-liner used on cards
   */
  description: string;
  /**
   * Wide intro shown at the top of the service page
   */
  overview?: string | null;
  /**
   * Emoji or short glyph, e.g. </> or ✦
   */
  icon?: string | null;
  accent?:
    | (
        | 'from-cyan-glow to-violet-glow'
        | 'from-violet-glow to-pink-glow'
        | 'from-pink-glow to-cyan-glow'
        | 'from-cyan-glow to-pink-glow'
        | 'from-violet-glow to-cyan-glow'
      )
    | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        benefit: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Detailed content blocks on the service page
   */
  sections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional pricing tiers shown on this service's page
   */
  pricing?:
    | {
        name: string;
        /**
         * e.g. from $990 — leave blank for 'Get a quote'
         */
        price?: string | null;
        /**
         * e.g. once-off, per month
         */
        unit?: string | null;
        features?:
          | {
              feature: string;
              id?: string | null;
            }[]
          | null;
        highlight?: boolean | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers show first
   */
  order?: number | null;
  /**
   * Optional search / social overrides. Leave blank to use the page defaults.
   */
  seo?: {
    /**
     * Overrides the <title> (≤ 60 chars ideal)
     */
    metaTitle?: string | null;
    /**
     * Overrides the meta description (≤ 155 chars ideal)
     */
    metaDescription?: string | null;
    /**
     * Social share image (og:image)
     */
    ogImage?: (number | null) | Media;
    /**
     * Absolute canonical URL, if different from this page
     */
    canonical?: string | null;
    /**
     * Hide this page from search engines
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * URL segment, e.g. web-hosting
   */
  slug: string;
  /**
   * Short one-liner used on cards
   */
  description: string;
  /**
   * Wide intro on the product page
   */
  overview?: string | null;
  icon?: string | null;
  /**
   * External order link (hosting portal)
   */
  href: string;
  price?: string | null;
  /**
   * Show the 'Popular' badge
   */
  highlight?: boolean | null;
  bullets?:
    | {
        bullet: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Detailed content blocks on the product page
   */
  sections?:
    | {
        heading: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software".
 */
export interface Software {
  id: number;
  /**
   * e.g. Microsoft 365
   */
  name: string;
  /**
   * Vendor, e.g. Microsoft
   */
  brand?: string | null;
  category?:
    | ('Productivity' | 'Creative' | 'Communication' | 'Dev Tools' | 'Storage' | 'Security' | 'Cloud' | 'Other')
    | null;
  /**
   * 1–2 char badge, e.g. M
   */
  letter?: string | null;
  /**
   * Badge colour hex, e.g. #0078D4
   */
  color?: string | null;
  tagline?: string | null;
  active?: boolean | null;
  /**
   * Lower shows first
   */
  order?: number | null;
  plans?:
    | {
        /**
         * e.g. Business Standard
         */
        name: string;
        /**
         * AUD ex-GST
         */
        price?: number | null;
        unit?: string | null;
        /**
         * Short inclusions line
         */
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  addons?:
    | {
        name: string;
        /**
         * AUD ex-GST / month
         */
        price?: number | null;
        desc?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client reviews. Public submissions arrive unapproved — tick Approved to publish.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  quote: string;
  name: string;
  /**
   * e.g. Practice Manager
   */
  role?: string | null;
  company?: string | null;
  /**
   * Star rating 1–5. Feeds the aggregate rating shown in search results.
   */
  rating?: number | null;
  /**
   * Untick to hide. Public submissions start unapproved.
   */
  approved?: boolean | null;
  /**
   * Set automatically for public submissions.
   */
  submittedAt?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL segment, e.g. why-website-speed-matters
   */
  slug: string;
  /**
   * Short summary shown on cards & meta description
   */
  excerpt: string;
  coverImage?: (number | null) | Media;
  category?: string | null;
  author?: string | null;
  /**
   * Drafts are hidden from the public blog
   */
  status?: ('draft' | 'published') | null;
  date: string;
  /**
   * Estimated read time in minutes
   */
  readMins?: number | null;
  /**
   * Plain-text fallback body. Separate paragraphs with a blank line.
   */
  body: string;
  /**
   * Rich formatted article (headings, lists, links, inline images). When set, it replaces the plain body on the site.
   */
  richBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Link a full author profile (bio + photo). Overrides the plain Author text on the article.
   */
  authorProfile?: (number | null) | Author;
  /**
   * Optional search / social overrides. Leave blank to use the page defaults.
   */
  seo?: {
    /**
     * Overrides the <title> (≤ 60 chars ideal)
     */
    metaTitle?: string | null;
    /**
     * Overrides the meta description (≤ 155 chars ideal)
     */
    metaDescription?: string | null;
    /**
     * Social share image (og:image)
     */
    ogImage?: (number | null) | Media;
    /**
     * Absolute canonical URL, if different from this page
     */
    canonical?: string | null;
    /**
     * Hide this page from search engines
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Bylines for blog articles — name, role, short bio and photo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  /**
   * e.g. Lead Engineer, Founder
   */
  role?: string | null;
  /**
   * A sentence or two shown under the article.
   */
  bio?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  service?: string | null;
  message: string;
  status?: ('new' | 'qualified' | 'proposal' | 'won' | 'lost') | null;
  /**
   * Salesperson responsible
   */
  owner?: (number | null) | User;
  /**
   * Auto-scored 0–100 on submit
   */
  score?: number | null;
  /**
   * Estimated deal value, AUD
   */
  value?: number | null;
  /**
   * Where this lead came from (captured automatically)
   */
  attribution?: {
    /**
     * utm_source
     */
    source?: string | null;
    /**
     * utm_medium
     */
    medium?: string | null;
    /**
     * utm_campaign
     */
    campaign?: string | null;
    referrer?: string | null;
    landingPage?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  category: 'Google Workspace' | 'Microsoft 365' | 'Website Packages' | 'Marketing & SEO';
  name: string;
  blurb?: string | null;
  /**
   * AUD ex-GST, billed yearly (e.g. 8.40). Leave blank for 'Get a quote'.
   */
  priceAnnual?: string | null;
  /**
   * AUD ex-GST, flexible/monthly (e.g. 10.10).
   */
  priceMonthly?: string | null;
  /**
   * e.g. per user / month
   */
  unit?: string | null;
  features?:
    | {
        feature: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Show as the featured plan
   */
  highlight?: boolean | null;
  ctaLabel?: string | null;
  /**
   * Order link or /contact
   */
  ctaHref?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logoMedia?: (number | null) | Media;
  /**
   * Or paste a logo image URL (upload above is preferred)
   */
  logo?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  category?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  /**
   * Where they subscribed from (footer, blog, …)
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-articles".
 */
export interface HelpArticle {
  id: number;
  title: string;
  slug: string;
  category?: string | null;
  excerpt?: string | null;
  /**
   * Separate paragraphs with a blank line.
   */
  body: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  industry?: string | null;
  services?:
    | {
        service: string;
        id?: string | null;
      }[]
    | null;
  summary?: string | null;
  beforeMedia?: (number | null) | Media;
  afterMedia?: (number | null) | Media;
  /**
   * Or paste a 'before' image URL (upload preferred)
   */
  beforeImage?: string | null;
  /**
   * Or paste an 'after' image URL (upload preferred)
   */
  afterImage?: string | null;
  /**
   * Live site URL (optional)
   */
  url?: string | null;
  results?:
    | {
        result: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-requests".
 */
export interface DataRequest {
  id: number;
  email: string;
  type: 'export' | 'delete';
  details?: string | null;
  status?: ('new' | 'in-progress' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  name: string;
  company?: string | null;
  phone?: string | null;
  abn?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  suburb?: string | null;
  state?: string | null;
  postcode?: string | null;
  country?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'customers';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  customer?: (number | null) | Customer;
  items?:
    | {
        description: string;
        /**
         * e.g. monthly, annually, once-off
         */
        cycle?: string | null;
        quantity?: number | null;
        /**
         * ex-GST, AUD
         */
        unitPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * ex-GST, AUD
   */
  total?: number | null;
  status?: ('pending' | 'active' | 'cancelled' | 'fraud') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions".
 */
export interface Subscription {
  id: number;
  /**
   * e.g. Web Hosting — example.com.au
   */
  label: string;
  customer?: (number | null) | Customer;
  domain?: string | null;
  status?: ('pending' | 'active' | 'suspended' | 'terminated' | 'cancelled') | null;
  /**
   * monthly, annually, …
   */
  billingCycle?: string | null;
  /**
   * ex-GST, AUD
   */
  recurringAmount?: number | null;
  nextDueDate?: string | null;
  /**
   * e.g. cPanel username (Phase 3)
   */
  provisioningRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  /**
   * Auto-generated on create if left blank
   */
  number?: string | null;
  customer?: (number | null) | Customer;
  /**
   * Set automatically for renewal invoices; links dunning back to the service
   */
  subscription?: (number | null) | Subscription;
  items?:
    | {
        description: string;
        quantity?: number | null;
        /**
         * ex-GST line total, AUD
         */
        amount?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotal?: number | null;
  /**
   * GST
   */
  tax?: number | null;
  total?: number | null;
  status?: ('unpaid' | 'paid' | 'overdue' | 'refunded' | 'cancelled') | null;
  dueDate?: string | null;
  paidDate?: string | null;
  /**
   * Dunning reminders emailed so far
   */
  remindersSent?: number | null;
  lastReminderAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: number;
  reference?: string | null;
  invoice?: (number | null) | Invoice;
  customer?: (number | null) | Customer;
  gateway?: string | null;
  amount?: number | null;
  status?: ('pending' | 'succeeded' | 'failed' | 'refunded') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-domains".
 */
export interface ClientDomain {
  id: number;
  domain: string;
  customer?: (number | null) | Customer;
  registrar?: string | null;
  registeredDate?: string | null;
  expiryDate?: string | null;
  autoRenew?: boolean | null;
  status?: ('pending' | 'active' | 'expired' | 'transferred-away') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hardware, software and licenses per client — with renewal dates for reminders and upsell.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets".
 */
export interface Asset {
  id: number;
  /**
   * e.g. Dell Latitude 5450, Microsoft 365 Business Premium
   */
  name: string;
  /**
   * The client this asset belongs to
   */
  customer?: (number | null) | Customer;
  category?: ('hardware' | 'software' | 'license' | 'subscription' | 'other') | null;
  /**
   * e.g. Dell, Microsoft, Adobe
   */
  vendor?: string | null;
  /**
   * Serial / asset tag / license key
   */
  identifier?: string | null;
  /**
   * Seats / units
   */
  quantity?: number | null;
  /**
   * ex-GST AUD per unit — used for renewal value / upsell
   */
  unitCost?: number | null;
  purchaseDate?: string | null;
  /**
   * Warranty end / license or subscription renewal date
   */
  renewalDate?: string | null;
  /**
   * Auto-set from the renewal date unless 'retired'.
   */
  status?: ('active' | 'expiring' | 'expired' | 'retired') | null;
  /**
   * Email the client before this renews
   */
  autoRemind?: boolean | null;
  /**
   * Set when a renewal reminder was last sent
   */
  lastReminderAt?: string | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets".
 */
export interface Ticket {
  id: number;
  subject: string;
  customer?: (number | null) | Customer;
  /**
   * Engineer responsible for this ticket
   */
  assignee?: (number | null) | User;
  department?: ('support' | 'billing' | 'sales') | null;
  status?: ('open' | 'answered' | 'customer-reply' | 'closed') | null;
  priority?: ('low' | 'medium' | 'high') | null;
  /**
   * First-response SLA deadline
   */
  slaDueAt?: string | null;
  firstRespondedAt?: string | null;
  resolvedAt?: string | null;
  messages?:
    | {
        author?: string | null;
        /**
         * Was this reply from our team?
         */
        staff?: boolean | null;
        message: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  type?: ('percent' | 'fixed') | null;
  value: number;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Privacy, Terms, etc. Fill the body to override the built-in page text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: number;
  title: string;
  /**
   * Must match the page path: privacy, terms, acceptable-use, or refund-policy
   */
  slug: string;
  /**
   * Rich text. When set, it replaces the built-in page content.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * URL segment, e.g. clinic
   */
  slug: string;
  /**
   * Short card summary
   */
  summary: string;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Glyph shown on the card, e.g. + or ⚿
   */
  mark?: string | null;
  /**
   * CSS gradient for the card, e.g. linear-gradient(135deg,#3F3DCC,#5E5BFF)
   */
  gradient?: string | null;
  /**
   * Headline result numbers
   */
  metrics?:
    | {
        /**
         * Value, e.g. 0 hrs
         */
        k: string;
        /**
         * Label, e.g. Downtime
         */
        v: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The Challenge / What we did / The outcome blocks
   */
  sections?:
    | {
        head: string;
        body: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Client testimonial quote
   */
  quote?: string | null;
  author?: string | null;
  authorRole?: string | null;
  authorInitials?: string | null;
  /**
   * Lower numbers show first
   */
  order?: number | null;
  /**
   * Optional search / social overrides. Leave blank to use the page defaults.
   */
  seo?: {
    /**
     * Overrides the <title> (≤ 60 chars ideal)
     */
    metaTitle?: string | null;
    /**
     * Overrides the meta description (≤ 155 chars ideal)
     */
    metaDescription?: string | null;
    /**
     * Social share image (og:image)
     */
    ogImage?: (number | null) | Media;
    /**
     * Absolute canonical URL, if different from this page
     */
    canonical?: string | null;
    /**
     * Hide this page from search engines
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  /**
   * Auto-generated
   */
  number?: string | null;
  prospectName: string;
  prospectEmail: string;
  /**
   * Link once they're a client
   */
  customer?: (number | null) | Customer;
  /**
   * e.g. Managed IT proposal
   */
  title?: string | null;
  /**
   * Optional summary shown above the line items
   */
  intro?: string | null;
  items?:
    | {
        description: string;
        quantity?: number | null;
        /**
         * ex-GST, AUD
         */
        unitPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotal?: number | null;
  /**
   * GST
   */
  tax?: number | null;
  total?: number | null;
  status?: ('draft' | 'sent' | 'accepted' | 'declined' | 'expired') | null;
  validUntil?: string | null;
  /**
   * Used in the public accept link
   */
  acceptToken?: string | null;
  acceptedAt?: string | null;
  /**
   * Set when the prospect pays online via Stripe
   */
  paidAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Services shown on the public status page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-components".
 */
export interface SystemComponent {
  id: number;
  name: string;
  description?: string | null;
  status?: ('operational' | 'degraded' | 'partial' | 'major' | 'maintenance') | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Incidents & maintenance shown on the public status page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents".
 */
export interface Incident {
  id: number;
  title: string;
  severity?: ('maintenance' | 'minor' | 'major' | 'critical') | null;
  status?: ('investigating' | 'identified' | 'monitoring' | 'resolved') | null;
  /**
   * Components affected by this incident
   */
  affected?: (number | SystemComponent)[] | null;
  /**
   * Timeline of updates, newest last
   */
  updates?:
    | {
        status?: ('investigating' | 'identified' | 'monitoring' | 'resolved') | null;
        body: string;
        /**
         * Defaults to now if blank
         */
        at?: string | null;
        id?: string | null;
      }[]
    | null;
  startedAt?: string | null;
  resolvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * New-client onboarding checklists. Auto-created when a customer is added.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding".
 */
export interface Onboarding {
  id: number;
  customer?: (number | null) | Customer;
  status?: ('active' | 'complete') | null;
  steps?:
    | {
        label: string;
        done?: boolean | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * People subscribed to incident/maintenance email alerts.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-subscribers".
 */
export interface StatusSubscriber {
  id: number;
  email: string;
  confirmed?: boolean | null;
  /**
   * Unsubscribe token
   */
  token?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 301/302 redirects enforced site-wide. Protects SEO when URLs change.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Source path, e.g. /old-page (leading slash, no domain)
   */
  from: string;
  /**
   * Target path or absolute URL, e.g. /new-page or https://…
   */
  to: string;
  /**
   * On = 301 (permanent). Off = 302 (temporary).
   */
  permanent?: boolean | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'software';
        value: number | Software;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'help-articles';
        value: number | HelpArticle;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'data-requests';
        value: number | DataRequest;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'subscriptions';
        value: number | Subscription;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'transactions';
        value: number | Transaction;
      } | null)
    | ({
        relationTo: 'client-domains';
        value: number | ClientDomain;
      } | null)
    | ({
        relationTo: 'assets';
        value: number | Asset;
      } | null)
    | ({
        relationTo: 'tickets';
        value: number | Ticket;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'system-components';
        value: number | SystemComponent;
      } | null)
    | ({
        relationTo: 'incidents';
        value: number | Incident;
      } | null)
    | ({
        relationTo: 'onboarding';
        value: number | Onboarding;
      } | null)
    | ({
        relationTo: 'status-subscribers';
        value: number | StatusSubscriber;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'customers';
        value: number | Customer;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  tagline?: T;
  description?: T;
  overview?: T;
  icon?: T;
  accent?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        benefit?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        name?: T;
        price?: T;
        unit?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        highlight?: T;
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  overview?: T;
  icon?: T;
  href?: T;
  price?: T;
  highlight?: T;
  bullets?:
    | T
    | {
        bullet?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        heading?: T;
        body?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software_select".
 */
export interface SoftwareSelect<T extends boolean = true> {
  name?: T;
  brand?: T;
  category?: T;
  letter?: T;
  color?: T;
  tagline?: T;
  active?: T;
  order?: T;
  plans?:
    | T
    | {
        name?: T;
        price?: T;
        unit?: T;
        feature?: T;
        id?: T;
      };
  addons?:
    | T
    | {
        name?: T;
        price?: T;
        desc?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  name?: T;
  role?: T;
  company?: T;
  rating?: T;
  approved?: T;
  submittedAt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  category?: T;
  author?: T;
  status?: T;
  date?: T;
  readMins?: T;
  body?: T;
  richBody?: T;
  authorProfile?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  service?: T;
  message?: T;
  status?: T;
  owner?: T;
  score?: T;
  value?: T;
  attribution?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        referrer?: T;
        landingPage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  blurb?: T;
  priceAnnual?: T;
  priceMonthly?: T;
  unit?: T;
  features?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  highlight?: T;
  ctaLabel?: T;
  ctaHref?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logoMedia?: T;
  logo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-articles_select".
 */
export interface HelpArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  body?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  industry?: T;
  services?:
    | T
    | {
        service?: T;
        id?: T;
      };
  summary?: T;
  beforeMedia?: T;
  afterMedia?: T;
  beforeImage?: T;
  afterImage?: T;
  url?: T;
  results?:
    | T
    | {
        result?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-requests_select".
 */
export interface DataRequestsSelect<T extends boolean = true> {
  email?: T;
  type?: T;
  details?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  phone?: T;
  abn?: T;
  addressLine1?: T;
  addressLine2?: T;
  suburb?: T;
  state?: T;
  postcode?: T;
  country?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customer?: T;
  items?:
    | T
    | {
        description?: T;
        cycle?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  total?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscriptions_select".
 */
export interface SubscriptionsSelect<T extends boolean = true> {
  label?: T;
  customer?: T;
  domain?: T;
  status?: T;
  billingCycle?: T;
  recurringAmount?: T;
  nextDueDate?: T;
  provisioningRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  number?: T;
  customer?: T;
  subscription?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        amount?: T;
        id?: T;
      };
  subtotal?: T;
  tax?: T;
  total?: T;
  status?: T;
  dueDate?: T;
  paidDate?: T;
  remindersSent?: T;
  lastReminderAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  reference?: T;
  invoice?: T;
  customer?: T;
  gateway?: T;
  amount?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-domains_select".
 */
export interface ClientDomainsSelect<T extends boolean = true> {
  domain?: T;
  customer?: T;
  registrar?: T;
  registeredDate?: T;
  expiryDate?: T;
  autoRenew?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assets_select".
 */
export interface AssetsSelect<T extends boolean = true> {
  name?: T;
  customer?: T;
  category?: T;
  vendor?: T;
  identifier?: T;
  quantity?: T;
  unitCost?: T;
  purchaseDate?: T;
  renewalDate?: T;
  status?: T;
  autoRemind?: T;
  lastReminderAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tickets_select".
 */
export interface TicketsSelect<T extends boolean = true> {
  subject?: T;
  customer?: T;
  assignee?: T;
  department?: T;
  status?: T;
  priority?: T;
  slaDueAt?: T;
  firstRespondedAt?: T;
  resolvedAt?: T;
  messages?:
    | T
    | {
        author?: T;
        staff?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  type?: T;
  value?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  mark?: T;
  gradient?: T;
  metrics?:
    | T
    | {
        k?: T;
        v?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        head?: T;
        body?: T;
        id?: T;
      };
  quote?: T;
  author?: T;
  authorRole?: T;
  authorInitials?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        canonical?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  number?: T;
  prospectName?: T;
  prospectEmail?: T;
  customer?: T;
  title?: T;
  intro?: T;
  items?:
    | T
    | {
        description?: T;
        quantity?: T;
        unitPrice?: T;
        id?: T;
      };
  subtotal?: T;
  tax?: T;
  total?: T;
  status?: T;
  validUntil?: T;
  acceptToken?: T;
  acceptedAt?: T;
  paidAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "system-components_select".
 */
export interface SystemComponentsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  status?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "incidents_select".
 */
export interface IncidentsSelect<T extends boolean = true> {
  title?: T;
  severity?: T;
  status?: T;
  affected?: T;
  updates?:
    | T
    | {
        status?: T;
        body?: T;
        at?: T;
        id?: T;
      };
  startedAt?: T;
  resolvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "onboarding_select".
 */
export interface OnboardingSelect<T extends boolean = true> {
  customer?: T;
  status?: T;
  steps?:
    | T
    | {
        label?: T;
        done?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "status-subscribers_select".
 */
export interface StatusSubscribersSelect<T extends boolean = true> {
  email?: T;
  confirmed?: T;
  token?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  permanent?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  /**
   * Headline numbers shown on the homepage & about page
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The 'How we work' steps on the homepage
   */
  processSteps?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The top section of the homepage. Blank fields use the built-in defaults.
   */
  hero?: {
    /**
     * Small pill above the heading, e.g. 'Now onboarding new clients · 2026'
     */
    eyebrow?: string | null;
    /**
     * Main H1. Plain text — overrides the styled default when set.
     */
    heading?: string | null;
    subheading?: string | null;
    ctaPrimaryLabel?: string | null;
    ctaPrimaryHref?: string | null;
    ctaSecondaryLabel?: string | null;
    ctaSecondaryHref?: string | null;
  };
  /**
   * The big indigo call-to-action band near the bottom of the homepage.
   */
  closingCta?: {
    heading?: string | null;
    subheading?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Eyebrow / heading / subheading for the top of each marketing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content".
 */
export interface PageContent {
  id: number;
  /**
   * One row per page. 'page' must match the page key (about, careers, services, pricing).
   */
  headers?:
    | {
        /**
         * Page key: about, careers, services, pricing
         */
        page: string;
        /**
         * Small label above the heading
         */
        eyebrow?: string | null;
        /**
         * Plain text; overrides the styled default when set
         */
        heading?: string | null;
        subheading?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Copy on the /contact page. Phone & email come from Site Settings.
   */
  contact?: {
    /**
     * Small label above the heading
     */
    eyebrow?: string | null;
    /**
     * Main heading
     */
    heading?: string | null;
    /**
     * Lead paragraph under the heading
     */
    subheading?: string | null;
  };
  /**
   * Body copy on the /about page (below the header).
   */
  about?: {
    /**
     * One or more paragraphs of intro copy.
     */
    intro?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Heading above the values grid
     */
    valuesHeading?: string | null;
    /**
     * Heading above the timeline
     */
    timelineHeading?: string | null;
    /**
     * Milestones shown in 'The story so far'.
     */
    timeline?:
      | {
          year: string;
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Brand, contact details, socials and footer — used site-wide.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * e.g. SyberInfo
   */
  name?: string | null;
  /**
   * e.g. SyberInfo Pty Ltd
   */
  legalName?: string | null;
  tagline?: string | null;
  /**
   * Default meta description / brand blurb
   */
  description?: string | null;
  email?: string | null;
  /**
   * Display phone, e.g. 1300 000 000
   */
  phone?: string | null;
  /**
   * International format for tel: links, e.g. +61300000000
   */
  phoneIntl?: string | null;
  address?: string | null;
  abn?: string | null;
  /**
   * e.g. Mon–Fri 8am–6pm AEST
   */
  hours?: string | null;
  /**
   * WhatsApp number, digits only; blank hides the button
   */
  whatsapp?: string | null;
  social?: {
    linkedin?: string | null;
    twitter?: string | null;
    github?: string | null;
    facebook?: string | null;
    instagram?: string | null;
  };
  /**
   * Footer link columns. Leave empty to use the built-in defaults.
   */
  footerColumns?:
    | {
        heading: string;
        links?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-settings".
 */
export interface BillingSetting {
  id: number;
  companyLegalName?: string | null;
  abn?: string | null;
  addressLines?: string | null;
  /**
   * GST percentage
   */
  gstRate?: number | null;
  gstRegistered?: boolean | null;
  invoicePrefix?: string | null;
  invoiceNextNumber?: number | null;
  /**
   * Days overdue before suspension
   */
  gracePeriodDays?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  processSteps?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subheading?: T;
        ctaPrimaryLabel?: T;
        ctaPrimaryHref?: T;
        ctaSecondaryLabel?: T;
        ctaSecondaryHref?: T;
      };
  closingCta?:
    | T
    | {
        heading?: T;
        subheading?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content_select".
 */
export interface PageContentSelect<T extends boolean = true> {
  headers?:
    | T
    | {
        page?: T;
        eyebrow?: T;
        heading?: T;
        subheading?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        subheading?: T;
      };
  about?:
    | T
    | {
        intro?:
          | T
          | {
              text?: T;
              id?: T;
            };
        valuesHeading?: T;
        timelineHeading?: T;
        timeline?:
          | T
          | {
              year?: T;
              text?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  name?: T;
  legalName?: T;
  tagline?: T;
  description?: T;
  email?: T;
  phone?: T;
  phoneIntl?: T;
  address?: T;
  abn?: T;
  hours?: T;
  whatsapp?: T;
  social?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        github?: T;
        facebook?: T;
        instagram?: T;
      };
  footerColumns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "billing-settings_select".
 */
export interface BillingSettingsSelect<T extends boolean = true> {
  companyLegalName?: T;
  abn?: T;
  addressLines?: T;
  gstRate?: T;
  gstRegistered?: T;
  invoicePrefix?: T;
  invoiceNextNumber?: T;
  gracePeriodDays?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}