import type { Metadata } from "next";
import { Aurora, SectionHeading } from "@/components/ui";
import SeoAuditTool from "@/components/SeoAuditTool";

export const metadata: Metadata = {
  title: "Free Website & SEO Audit",
  description:
    "Get an instant, free performance and SEO score for your website, powered by Google Lighthouse — plus tips to improve.",
};

export default function SeoAuditPage() {
  return (
    <div className="relative pt-36 pb-12">
      <Aurora />
      <div className="mx-auto max-w-4xl px-5">
        <SectionHeading
          eyebrow="Free tool"
          title={
            <>
              Free website &amp; <span className="text-gradient">SEO audit</span>
            </>
          }
          subtitle="Enter your URL for an instant performance, SEO, accessibility and best-practices score — powered by Google Lighthouse."
        />
        <div className="mt-12">
          <SeoAuditTool />
        </div>
        <p className="mx-auto mt-6 max-w-2xl text-center text-xs text-muted">
          Scores are generated by Google PageSpeed Insights (Lighthouse, mobile).
          They&apos;re a great starting point — book a chat for a full,
          human review.
        </p>
      </div>
    </div>
  );
}
